---
- name: add openvpn key
  apt_key:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    state: present

- name: add openvpn repo
  apt_repository:
    repo: "deb http://build.openvpn.net/debian/openvpn/stable {{ ansible_distribution_release }} main"
    filename: "openvpn"
    state: present

- name: install packages
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - openvpn

- name: setup openvpn group
  group:
    name: "{{ openvpn_group }}"
    state: present
    system: yes

- name: setup openvpn user
  user:
    name: "{{ openvpn_user }}"
    state: present
    system: yes
    createhome: no
    group: "{{ openvpn_group }}"

- name: add server.conf
  template:
    src: server.conf.j2
    dest: "/etc/openvpn/server.conf"
    owner: root
    group: root
    mode: "0644"

- name: add ca.crt
  copy:
    src: "{{ openvpn_import_directory }}/{{ openvpn_ca_crt_filename }}"
    dest: /etc/openvpn/ca.crt
    owner: root
    group: root
    mode: 0644

- name: add server.crt
  copy:
    src: "{{ openvpn_import_directory }}/{{ openvpn_server_crt_filename }}"
    dest: /etc/openvpn/server.crt
    owner: root
    group: root
    mode: 0644

- name: add server.key
  copy:
    src: "{{ openvpn_import_directory }}/{{ openvpn_server_key_filename }}"
    dest: /etc/openvpn/server.key
    owner: root
    group: root
    mode: 0644

- name: add dh.pem
  copy:
    src: "{{ openvpn_import_directory }}/{{ openvpn_dh_filename }}"
    dest: "/etc/openvpn/{{ openvpn_dh_filename }}"
    owner: root
    group: root
    mode: 0644

- name: add ta.key
  copy:
    src: "{{ openvpn_import_directory }}/{{ openvpn_server_key_filename }}"
    dest: /etc/openvpn/ta.key
    owner: root
    group: root
    mode: 0644

- name: create staticclients directory
  file:
    path: /etc/openvpn/staticclients
    state: directory
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: "0755"

- name: add client IP
  template:
    src: staticclient.j2
    dest: "/etc/openvpn/staticclients/{{ item.name }}"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: "0644"
  with_items: "{{ openvpn_static_clients }}"

- name: activate ipv4 forwarding
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^net.ipv4.ip_forward"
    line: "net.ipv4.ip_forward=1"
    state: present

- name: activate forwarding
  command: sysctl -p

- name: openvpn restart
  systemd:
    name: openvpn
    state: restarted

...
